#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSM.Integration.Lubrizol.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Lubrizol")]
	public partial class LubrizolDataModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LubrizolDataModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LubrizolDataModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LubrizolDataModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LubrizolDataModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblzILMData> tblzILMDatas
		{
			get
			{
				return this.GetTable<tblzILMData>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblzILMData")]
	public partial class tblzILMData
	{
		
		private string _EmployeeID;
		
		private string _Initials;
		
		private string _Name;
		
		private string _ReportingLocation;
		
		private string _ReportingLocationName;
		
		private string _PhysicalLocation;
		
		private string _PhysicalLocationName;
		
		private char _EmployeeStatus;
		
		private string _EmployeeStatusDesc;
		
		private string _Department;
		
		private string _DepartmentName;
		
		private string _EmployeeClassDesc;
		
		private string _Division;
		
		private string _LegalEntity;
		
		private string _Company;
		
		private string _JobDescr;
		
		private string _SupervisorID;
		
		private string _SupervisorInitials;
		
		private string _SupervisorName;
		
		private string _FirstName;
		
		private string _MiddleName;
		
		private string _LastName;
		
		private string _Country;
		
		private System.Nullable<System.DateTime> _LastLoadDate;
		
		public tblzILMData()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="NChar(8) NOT NULL", CanBeNull=false)]
		public string EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this._EmployeeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Initials", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Initials
		{
			get
			{
				return this._Initials;
			}
			set
			{
				if ((this._Initials != value))
				{
					this._Initials = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportingLocation", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
		public string ReportingLocation
		{
			get
			{
				return this._ReportingLocation;
			}
			set
			{
				if ((this._ReportingLocation != value))
				{
					this._ReportingLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportingLocationName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string ReportingLocationName
		{
			get
			{
				return this._ReportingLocationName;
			}
			set
			{
				if ((this._ReportingLocationName != value))
				{
					this._ReportingLocationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysicalLocation", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
		public string PhysicalLocation
		{
			get
			{
				return this._PhysicalLocation;
			}
			set
			{
				if ((this._PhysicalLocation != value))
				{
					this._PhysicalLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysicalLocationName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PhysicalLocationName
		{
			get
			{
				return this._PhysicalLocationName;
			}
			set
			{
				if ((this._PhysicalLocationName != value))
				{
					this._PhysicalLocationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeStatus", DbType="NChar(1) NOT NULL")]
		public char EmployeeStatus
		{
			get
			{
				return this._EmployeeStatus;
			}
			set
			{
				if ((this._EmployeeStatus != value))
				{
					this._EmployeeStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeStatusDesc", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string EmployeeStatusDesc
		{
			get
			{
				return this._EmployeeStatusDesc;
			}
			set
			{
				if ((this._EmployeeStatusDesc != value))
				{
					this._EmployeeStatusDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(10)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentName", DbType="NVarChar(40)")]
		public string DepartmentName
		{
			get
			{
				return this._DepartmentName;
			}
			set
			{
				if ((this._DepartmentName != value))
				{
					this._DepartmentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeClassDesc", DbType="NVarChar(20)")]
		public string EmployeeClassDesc
		{
			get
			{
				return this._EmployeeClassDesc;
			}
			set
			{
				if ((this._EmployeeClassDesc != value))
				{
					this._EmployeeClassDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Division", DbType="NVarChar(40)")]
		public string Division
		{
			get
			{
				return this._Division;
			}
			set
			{
				if ((this._Division != value))
				{
					this._Division = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegalEntity", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
		public string LegalEntity
		{
			get
			{
				return this._LegalEntity;
			}
			set
			{
				if ((this._LegalEntity != value))
				{
					this._LegalEntity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(30)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobDescr", DbType="NVarChar(40)")]
		public string JobDescr
		{
			get
			{
				return this._JobDescr;
			}
			set
			{
				if ((this._JobDescr != value))
				{
					this._JobDescr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupervisorID", DbType="NChar(8)")]
		public string SupervisorID
		{
			get
			{
				return this._SupervisorID;
			}
			set
			{
				if ((this._SupervisorID != value))
				{
					this._SupervisorID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupervisorInitials", DbType="NVarChar(30)")]
		public string SupervisorInitials
		{
			get
			{
				return this._SupervisorInitials;
			}
			set
			{
				if ((this._SupervisorInitials != value))
				{
					this._SupervisorInitials = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupervisorName", DbType="NVarChar(50)")]
		public string SupervisorName
		{
			get
			{
				return this._SupervisorName;
			}
			set
			{
				if ((this._SupervisorName != value))
				{
					this._SupervisorName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(40)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(40)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this._MiddleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(40)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(40)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoadDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLoadDate
		{
			get
			{
				return this._LastLoadDate;
			}
			set
			{
				if ((this._LastLoadDate != value))
				{
					this._LastLoadDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
