CREATE TABLE [dbo].[People] (
    [PersonID]               INT             IDENTITY (1, 1) NOT NULL,
    [FirstName]              NVARCHAR (50)   NOT NULL,
    [LastName]               NVARCHAR (50)   NOT NULL,
    [MiddleName]             NVARCHAR (50)   NULL,
    [DeptID]                 NVARCHAR (50)   NULL,
    [DeptDescr]              NVARCHAR (50)   NULL,
    [JobCode]                NVARCHAR (50)   NULL,
    [JobDescr]               NVARCHAR (50)   NULL,
    [BadgeNumber]            NVARCHAR (50)   NULL,
    [Facility]               NVARCHAR (50)   NULL,
    [Active]                 BIT             NOT NULL,
    [LastUpdated]            DATETIME        NOT NULL,
    [LastUpdateMask]         INT             CONSTRAINT [DF_People_LastUpdateMask] DEFAULT ((0)) NOT NULL,
    [username]               NCHAR (10)      NULL,
    [password]               NVARCHAR (MAX)  NULL,
    [LastLogin]              DATETIME        NULL,
    [LastActivity]           DATETIME        NULL,
    [FailedPasswordAttempts] INT             CONSTRAINT [DF_People_FailedPasswordAttempts] DEFAULT ((0)) NOT NULL,
    [LockedOut]              BIT             CONSTRAINT [DF_People_LockedOut] DEFAULT ((0)) NOT NULL,
    [IsAdmin]                BIT             CONSTRAINT [DF_People_IsAdmin] DEFAULT ((0)) NOT NULL,
    [NeedsApproval]          BIT             CONSTRAINT [DF_People_NeedsApproval] DEFAULT ((0)) NOT NULL,
    [NeedsRulePass]          BIT             CONSTRAINT [DF_People_NeedsRulePass] DEFAULT ((0)) NOT NULL,
    [NeedsUpload]            BIT             CONSTRAINT [DF_People_NeedsUpload] DEFAULT ((0)) NOT NULL,
    [EmployeeID]             VARCHAR (50)    NULL,
    [Credentials]            NVARCHAR (MAX)  NULL,
    [NickFirst]              NVARCHAR (MAX)  NULL,
    [UDF1]                   NVARCHAR (MAX)  NULL,
    [UDF2]                   NVARCHAR (MAX)  NULL,
    [UDF3]                   NVARCHAR (MAX)  NULL,
    [UDF4]                   NVARCHAR (MAX)  NULL,
    [UDF5]                   NVARCHAR (MAX)  NULL,
    [UDF6]                   NVARCHAR (MAX)  NULL,
    [UDF7]                   NVARCHAR (MAX)  NULL,
    [UDF8]                   NVARCHAR (MAX)  NULL,
    [UDF9]                   NVARCHAR (MAX)  NULL,
    [UDF10]                  NVARCHAR (MAX)  NULL,
    [UDF11]                  NVARCHAR (MAX)  NULL,
    [UDF12]                  NVARCHAR (MAX)  NULL,
    [UDF13]                  NVARCHAR (MAX)  NULL,
    [UDF14]                  NVARCHAR (MAX)  NULL,
    [UDF15]                  NVARCHAR (MAX)  NULL,
    [UDF16]                  NVARCHAR (MAX)  NULL,
    [UDF17]                  NVARCHAR (MAX)  NULL,
    [UDF18]                  NVARCHAR (MAX)  NULL,
    [UDF19]                  NVARCHAR (MAX)  NULL,
    [UDF20]                  NVARCHAR (MAX)  NULL,
    [Added]                  DATETIME        CONSTRAINT [DF__tmp_ms_xx__Added__52593CB8] DEFAULT (sysdatetime()) NOT NULL,
    [Image]                  VARBINARY (MAX) NULL,
    CONSTRAINT [PK_People] PRIMARY KEY CLUSTERED ([PersonID] ASC)
);



